name: Mail-only Gmail API test

on:
  workflow_dispatch: {}

jobs:
  mail:
    runs-on: ubuntu-latest
    environment: development # ← 環境名に置き換え
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONUTF8: "1"
      PYTHONIOENCODING: "UTF-8"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Google API deps
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth

      - name: Make dummy CSV
        run: |
          echo "col1,col2" > mail_test.csv
          echo "hello,world" >> mail_test.csv

      - name: Run mail-test script
        env:
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          CSV_EMAIL_RECIPIENTS: ${{ secrets.CSV_EMAIL_RECIPIENTS }}
        run: |
          python tmp.test_gmail_send.py mail_test.csv

      - name: Upload CSV artifact on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: mail_test.csv
          path: mail_test.csv
          retention-days: 1

      - name: Cleanup
        if: always()
        run: rm -f mail_test.csv || true
